# Generated by Django 2.0.1 on 2018-01-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=50)),
                ('screen_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
            ],
        ),
    ]
