# Generated by Django 2.0.1 on 2018-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0002_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created',
        ),
        migrations.AddField(
            model_name='tweet',
            name='created_at_in_sec',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
