# Generated by Django 2.0.1 on 2018-01-27 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0003_auto_20180126_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 15, 15, 32, 412350)),
        ),
    ]
